export const CAMPAIGN_TYPE_QUESTION = "نوع کمپین مدنظر خود را مشخص کنید";

export const CAMPAIGN_TYPES = [
  "کمپین Awareness",
  "کمپین لانچ و معرفی محصول",
  "کمپین Acquisition (جذب کاربر / مشتری)",
  "کمپین فروش",
  "کمپین Engagement (تعاملی)",
  "کمپین محتوایی",
  "کمپین Retention (حفظ مشتری)",
  "کمپین Revenue Expansion",
  "کمپین اجتماعی و برند",
  "کمپین رویداد",
  "کمپین خلاق و وایرال",
  "اکتیویشن",
  "Performance Marketing (مارکتینگ عملکردی / نتیجه‌محور)",
  "CRM & Data-Driven (داده‌محور و شخصی‌سازی‌شده)",
  "Partnership & Co-Branding (همکاری برندها)",
  "Employer Branding (برند کارفرمایی)",
  "Crisis Management / PR (مدیریت بحران و روابط عمومی)",
  "Customer Education (آموزشی و آگاهی‌بخش)"
] as const;

export const CAMPAIGN_KPI_MAP: Record<string, string[]> = {
  "کمپین Awareness": [
    "Brand Association",
    "Brand Impressions",
    "Brand Mentions",
    "Brand Reach",
    "Brand Search",
    "Brand Search Volume",
    "Brand Sentiment",
    "Brand search",
    "Engagement",
    "Engagement Rate",
    "Impressions",
    "Influencer Reach",
    "New Followers",
    "Preference Rate",
    "Product Impressions",
    "Product Reach",
    "Product Search Volume",
    "Reach",
    "Sentiment Change",
    "Share",
    "Story Completion",
    "Traffic",
    "Trust Index",
    "product page view",
    "reach"
  ],
  "کمپین لانچ و معرفی محصول": [
    "Activation Rate",
    "Attendance Rate",
    "Beta Usage Time",
    "Demo Requests",
    "Email Opt-ins",
    "Feedback Score",
    "Initial Sales",
    "Lead Quality",
    "Product Reach",
    "Sign-ups",
    "Sign-ups/Waitlist",
    "Social Mentions",
    "Teaser Engagement",
    "Teaser Shares",
    "Trial Sign-ups",
    "Trial-to-Paid Conv.",
    "Usage Frequency",
    "User Feedback",
    "orders / reserve",
    "view"
  ],
  "کمپین Acquisition (جذب کاربر / مشتری)": [
    "Affiliate Sales",
    "CAC",
    "CPL",
    "Click-through Rate",
    "Commission ROI",
    "Conversion Rate",
    "Cost Per Acquisition",
    "Cost Per Lead (CPL)",
    "First-time Buyers",
    "K-Factor",
    "Lead Quality Score",
    "Number of Leads",
    "Referral Rate",
    "Sign-up Rate",
    "Sign-up Volume",
    "new user count"
  ],
  "کمپین فروش": [
    "Average Order Value",
    "Bundles Sold",
    "Conversion Rate",
    "Cross-sell Rate",
    "Discount Usage",
    "Inventory Turnover",
    "Margin Impact",
    "Peak Traffic",
    "ROI",
    "Sales Growth",
    "Sales Volume",
    "Sales per Hour",
    "Seasonal Revenue",
    "Stock-out Time",
    "Total Revenue",
    "Velocity of Sales"
  ],
  "کمپین Engagement (تعاملی)": [
    "Avg Session Time",
    "Comments/Replies",
    "Completion Rate",
    "Content Shares",
    "Engagement Rate",
    "Hashtag Usage",
    "Lead Conversion",
    "New Followers",
    "Participation Rate",
    "Response Quality",
    "Result Shares",
    "Retention Rate",
    "Share Count",
    "Task Completion",
    "Total Entries",
    "User Participations",
    "Virality Rate",
    "Vote Count"
  ],
  "کمپین محتوایی": [
    "Average Rating",
    "Conversion Rate",
    "Engagement",
    "Hashtag Reach",
    "Number of Posts",
    "Number of Reviews",
    "Review Sentiment",
    "Video View Rate",
    "orders"
  ],
  "کمپین Retention (حفظ مشتری)": [
    "Action Rate",
    "Active Members",
    "CTR",
    "Churn Rate",
    "Email Open Rate",
    "Incremental Sales",
    "LTV",
    "Loyalty Score",
    "Member ARPU",
    "Open Rate",
    "Order Frequency",
    "Points Redemption",
    "ROI of Campaign",
    "Reactivated Users",
    "Recovered Revenue",
    "Redemption Rate",
    "Repeat Purchase",
    "Repeat Purchase Rate",
    "Retention Rate",
    "Subscription Rate",
    "Usage Rate",
    "View-through Conv.",
    "Win-back Rate",
    "orders"
  ],
  "کمپین Revenue Expansion": [
    "Add-on Sales",
    "Attach Rate",
    "Average Ticket Size",
    "Churn Reduction",
    "Conv. Rate",
    "Cross-sell Revenue",
    "Items per Order",
    "MRR Increase",
    "Penetration Rate",
    "Revenue per User",
    "Upgrade Rate",
    "Upsell Revenue"
  ],
  "کمپین اجتماعی و برند": [
    "Awareness Level",
    "Brand Loyalty",
    "Brand Reputation",
    "Community Impact",
    "Engagement",
    "Environmental Impact",
    "Funds Raised",
    "Media Mentions",
    "National Reach",
    "Number of Donors",
    "Participation",
    "Positive Sentiment",
    "Public Engagement",
    "Reach",
    "Social Impact Metric",
    "engagement rate"
  ],
  "کمپین رویداد": [
    "Attendance",
    "Attendee Count",
    "Brand Sentiment",
    "Content Downloads",
    "Conversion to Lead",
    "Engagement",
    "Lead Generation",
    "Leads Collected",
    "Post-event Buzz",
    "Q&A Participation",
    "Registrations",
    "Sales during Event",
    "Social Media Reach",
    "Speaker Engagement",
    "Total Attendance",
    "Watch Time",
    "reach"
  ],
  "کمپین خلاق و وایرال": [
    "Brand Mentions",
    "Brand Recall",
    "Earned Media Value",
    "Engagement",
    "Media Impressions",
    "Organic Reach",
    "Relevance Score",
    "Sentiment Score",
    "Shares",
    "Time Spent",
    "Viral Reach",
    "Word of Mouth",
    "orders",
    "share rate"
  ],
  "اکتیویشن": [
    "Brand Recall",
    "Brand search",
    "Conversion to Buy",
    "Coupon Redemptions",
    "Direct Experience",
    "Engagement",
    "Feedback Score",
    "Reach",
    "Samples Distributed",
    "Social Mentions",
    "engagement rate"
  ],
  "Performance Marketing (مارکتینگ عملکردی / نتیجه‌محور)": [],
  "CRM & Data-Driven (داده‌محور و شخصی‌سازی‌شده)": [],
  "Partnership & Co-Branding (همکاری برندها)": [],
  "Employer Branding (برند کارفرمایی)": [],
  "Crisis Management / PR (مدیریت بحران و روابط عمومی)": [],
  "Customer Education (آموزشی و آگاهی‌بخش)": []
};

export function getCampaignKpis(campaignType: string): string[] {
  return CAMPAIGN_KPI_MAP[campaignType] ?? [];
}
